### PR TITLE
[SDPA-3455] applying permission check to content moderation

### PR DESCRIPTION
**Pull request by vincent-gao**
## JIRA
https://digital-engagement.atlassian.net/browse/SDPA-3455

## Changes
1. alter `content_moderation.state_transition_validation` service to provide a custom service.

https://github.com/dpc-sdp/content-vic-gov-au/pull/781
https://github.com/dpc-sdp/tide_core/pull/125

### CODE REVIEW

**Comment by GROwen** [comment]
@vincent-gao I've added a comment to the JIRA issue to establish what the expected result should be. Once that's confirmed we can review solution direction.

**Comment by vincent-gao** [comment]
> @vincent-gao I've added a comment to the JIRA issue to establish what the expected result should be. Once that's confirmed we can review solution direction.

Thanks. @GROwen

**Comment by GROwen** [comment]
@vincent-gao It's better to manage this at the permissions system rather than the render system. I'm thinking this can be managed by performing an access check similar to the way [content_moderation does for access to latest revisions](https://git.drupalcode.org/project/drupal/blob/8.8.x/core/modules/content_moderation/src/Access/LatestRevisionCheck.php#L55).

**Comment by vincent-gao** [comment]
> @vincent-gao It's better to manage this at the permissions system rather than the render system. I'm thinking this can be managed by performing an access check similar to the way [content_moderation does for access to latest revisions](https://git.drupalcode.org/project/drupal/blob/8.8.x/core/modules/content_moderation/src/Access/LatestRevisionCheck.php#L55).

Thanks for your suggestion! @GROwen 

image

The moderation state form that shows on node view is an extra field form(see above), which is not managed by entity or route permissions system. I think the only way to control the pseudo field is by rendering. see https://git.drupalcode.org/project/drupal/blob/8.8.x/core/modules/content_moderation/src/EntityOperations.php#L274

**Pull request merged**
